### ISSUE TITLE
Inconsistent value types returned from tango ChannelObject for binary (boolean) values

### ISSUE THREAD

**Issue by HilbertCorsair** [mxcube/mxcubecore#1026] opened 2024-09-19 08:50 UTC
I noticed a strange behaviour while working on the the implementation of the SampleChanger in the MxCube Web app and I'm wondering if anyone has seen anything similar. I am working with Cats90 and CatsMaint classes and I noticed the issue in the _read_state method here : https://github.com/mxcube/mxcubecore/blob/dfb3ce4154a0f7ddeb2d72f9474e0661261de948/mxcubecore/HardwareObjects/Cats90.py#L1175
The _powered value returned by the get_value() function starts as a boolean at first but if a command is passed and the state changes the same get_value() method no longer returns a boolean but a numeric value.
This also happens when getting the Lid1State  and Powered values in the CatsMaintClass using a tango ChannelObject like this:
self._chnLid1State.get_value() 
the channel is defined here. 
https://github.com/mxcube/mxcubecore/blob/dfb3ce4154a0f7ddeb2d72f9474e0661261de948/mxcubecore/HardwareObjects/CatsMaint.py#L153 

get_value() applied on a channel object that should return a boolean, works as intended at startup but starts returning numeric values for both False and True states. 
Is there a safe and consistent way to get the ON / OFF and open/closed states from a device on the tango server? 
Is it OK to use something like self.a_DeviceProxy_object.Powered in stead of passing through a ChannelObject ?

**Comment by marcus-oscarsson** [comment] 2024-09-19 11:34
@HilbertCorsair, maybe I misunderstood something. If you call `self._chnState().get_value()` multiple times you first get a `boolean` return type but then if you perform a command in between you get a `integer` ?. What values are you getting, 0, or 1 or some other values ?

**Comment by HilbertCorsair** [comment] 2024-09-19 12:58
I  put print statements that print on the console the state parameters recived by the _decide_sate function in Cats90 
here : read_state() --calls--> ()_decide_state as the app is running:
https://github.com/mxcube/mxcubecore/blob/dfb3ce4154a0f7ddeb2d72f9474e0661261de948/mxcubecore/HardwareObjects/Cats90.py#L1193
 as well as the global_dict in the get_global_state method of CatsMaint:
https://github.com/mxcube/mxcubecore/blob/dfb3ce4154a0f7ddeb2d72f9474e0661261de948/mxcubecore/HardwareObjects/CatsMaint.py#L703
 As the app is running. When I start the app all prints are normal with boolean values but if I push a button on the UI and send a command like Power ON/OFF or lid open/closed the command is executed and the class state parameters are updated but the new values are no longer booleans but integers that seem like random numbers between -20000 and +20000. This happens regardless weather the command is sent from the UI or from Jive or a different application. Whenever the device state changes the boolean values comming from the get_value() method of their respective ChannelObject become integers.

**Comment by beteva** [comment] 2024-09-19 13:09
Well, it seems, as you have the same behaviour with jive, that is is not at all MXCuBE tango channel problem.   Could it be a problem how the state, coming from the robot is translated into a TANGO state. Have you looked at the commands on the robot level?

**Comment by marcus-oscarsson** [comment] 2024-09-19 13:42
Indeed, I think the problem is more on the Tango or robot side. Try to see if you get the same if you communicate directly with the robot and then later try with Tango.

You are very welcome to continue to ask questions here or send your question to the mailing list, but I will close this issue as its not an issue of the `ChannelObject`. Perhaps investigate the issue a bit more and possibly try to find someone with a similar sample changer.

**Comment by HilbertCorsair** [comment] 2024-09-20 08:09
It's what I initially suspected as well, but we haven't been able to find anything wrong with the device state on the tango server. Perhaps it could be the way tango handles events and open communication channels to the mxcubeweb app.  I managed to arrive at a working version of the UI for the sample changer controls by avoiding the ChannelObjects for boolean states and getting the state information from the DeviceProxy. (Small issue in this case is that depending on the device the response can be as a string like "True" or "true" which needs to be mapped onto the corresponding boolean) . 
I pushed the changes on my sample_changer branch on my fork. The idea is to use the preexisting classes PX1Cryotong and PX1CatsMaint  to override some attributes and methods in the Cats90 and CatsMaint classes from which they inherit. 
Here you can see the changes made to the state_dict of the get_global_state method  where the values are taken From the  DeviceProxy. 
https://github.com/HilbertCorsair/mxcubecore_SOLEIL_PX1/blob/80c382e564d27405c270bb8f58a3172107d645ff/mxcubecore/HardwareObjects/mockup/PX1CatsMaint.py#L124

This approach doesn't deal with the issue regarding boolean values coming from tango ChannelObjects, it avoids it. That problem still remains.

**Comment by marcus-oscarsson** [comment] 2024-09-20 09:13
You mention that you have this problem, from `Jive` as well, so then it points towards something on the Tango device server side or further "down stream" towards the device, right ?

**Comment by HilbertCorsair** [comment] 2024-09-20 09:41
Yes the problem seems to  be pretty low level. We are still looking into it.  I thought it might have something to do with the get_value method in the ChannelObject class. There are some vague comments there and a force argument that I haven't yet figured out how it works. 
https://github.com/mxcube/mxcubecore/blob/dfb3ce4154a0f7ddeb2d72f9474e0661261de948/mxcubecore/CommandContainer.py#L279

**Comment by fabcor-maxiv** [comment] 2024-09-20 10:21
The way I understood Dan's comments, the issue can be triggered by sending commands from Jive (and not just from MXCuBE). Which does not necessarily mean that the bug is outside of MXCuBE. As far as I understood the symptoms are still in MXCuBE (not in Jive).

**Comment by marcus-oscarsson** [comment] 2024-09-20 12:02
So that would then be good to get confirmed, do you also observe the issue from `Jive` @HilbertCorsair ?

**Comment by HilbertCorsair** [comment] 2024-09-24 16:57
You understood correctly @marcus-oscarsson . Sending commands from jive causes the boolean values fo the Sample Changer and SampleChangerMaint  to switch to numerical values in the running MXCuBE app. Only boolean values coming from ChannelObjects are afected. Getting the values from the DeviceProxy.attribute works fine.

**Comment by marcus-oscarsson** [comment] 2024-09-26 11:32
but what do you get if you read the same channels from jive ?

**Comment by marcus-oscarsson** [comment] 2024-09-26 11:33
I'am trying to isolate the problem so to speak

**Comment by HilbertCorsair** [comment] 2024-09-30 12:41
@marcus-oscarsson  We looked on the tango side and the same attributes such as  "Powered" or "di_Lid1Open" are always booleans. So far I only noticed this switch to numerical values inside MXCuBe after a change in the satate of the device.

**Comment by marcus-oscarsson** [comment] 2024-09-30 12:47
Ok, @elmjag  and the guys from MaxIV made this simulation tango device. Do you think it would be possible to try to
see if its reproducible with that:

https://github.com/mxcube/mxcubecore/blob/c3620f5844f8cd2a7e755d832e96a77646f6ac23/test/pytest/test_hwo_isara_maint.py#L13

Like this we could try to isolate the issue, fix and eventually add a test for it ?

**Comment by marcus-oscarsson** [comment] 2024-09-30 12:47
Reopning this as it seems like it is an issue with the Tango channel within mxcube

**Comment by fabcor-maxiv** [comment] 2024-09-30 12:52
> Ok, elmir and the guys from MaxIV made this simulation tango device.

@marcus-oscarsson, wrong `@`-name... you probably meant @elmjag.

@HilbertCorsair I can try to have a look, but I don't use the "Cats" stuff, I work with "Isara" code instead (which I might need to rewrite). I don't now if that makes a difference.

**Comment by marcus-oscarsson** [comment] 2024-09-30 12:57
Yes of course i meant @elmjag

**Comment by beteva** [comment] 2024-10-01 15:45
@HilbertCorsair, as we do not have cats device I did some tests with one of our devices and do not find the problem you describe. To narrow down you could see what is the return from your tango device as pure python - the way it is used by the channels. You could do it like this and check what the return type is:
```
import PyTango
device = PyTrango.DeviceProxy(my_device)
type(device.read_attribute("Powered").value)
```

**Comment by beteva** [comment] 2024-10-01 16:03
To continue with the test, again in python you could do:
```
from CommandContainer import CommandContainer
cc =  CommandContainer()
_chnPowered = cc.add_channel({"type": "tango", "name": "_chnPowered", "tangoname": my_device,  "polling": 300,}, "Powered",)
type(_chnPowered.get_value())
_chnPowered.set_value(True) or False, whatever you want
_chnPowered.update()
type(_chnPowered.get_value())


```

**Comment by HilbertCorsair** [comment] 2024-10-11 15:58
This is a strange problem and I've noticed a similar behavior when checking if a sample is loaded or not in the Cats90 class. I ren a test and there was nothing wrong with the ChannelObject itself. In my local test self._chnPowered.get_value() and _chnLid1State().get_value() return the right boolean as do the DeviceProxy.attribute. However although so far the tests  on ChannelObject.get_value() have passed successfully my problem persist in the App so at the moment I am looking into the connect_signal() method as the potential source of the problem.  I haven't fixed the issue yet but it might have something to do with the local device configuration and poling type perhaps.   https://github.com/mxcube/mxcubecore/blob/d2f176be239558a7fd3cb8452dc78b8dee8a8fd6/mxcubecore/CommandContainer.py#L196C9-L196C23

The problem is the value passed to the callback funtion in connect_signal() . On the one hand this value comes from the tango device, it is low level and outside the scope of the MXCuBE App on the other hand all tests so far are normal when reading values from the tango devices, pointing back to something wrong in the MXCuBE app. Perhaps the local device configuration since nobody else sees this problem.  There are ways to work around this problem but I would like to understand what is happening. 
As an example here is what I did with the Lid state in CatsMaint: 

```
   def _update_lid1_state(self, value):
        if not isinstance(value, bool):
            # Hacked to read the value from the device proxy instead of using the value passed as argument since the <value> argument is faulty and is somtimes a bollean other times a 'random' integer
            self._lid1state = not self.cats_device.isLidClosed
            print(f"LID 1 value is {value} of type {type(value)}--->changing to {not self._lid1state}")
            self.emit("lid1StateChanged", (not self._lid1state,))
            self._update_global_state()
        else :
            self._lid1state =  value
            self.emit("lid1StateChanged", (value,))
            self._update_global_state()
```

If the values passed to the callback function is not boolean the value is red directly from the DeviceProxy.
Here are some outputs while running the app and acting on the lid : 

LID 1 value is 2992 of type <class 'int'>--->changing to True
LID 1 value is 27440 of type <class 'int'>--->changing to False
LID 1 value is 21104 of type <class 'int'>--->changing to True
LID 1 value is 7856 of type <class 'int'>--->changing to False


Sometimes I also get : 
Updating sample is detected ... <23984> (this is strange)
Updating sample is detected ... <False> (this is normal)

this is comming from : 
```
 def _update_sample_is_detected(self, value):
        print(f"\nUpdating sample is detected ... <{value}>")
        self.emit("sampleIsDetected", (value,))
```
Here is something even stranger: 
I left the app running without anything interacting with any device. Without any action and no state changes actively triggered I still got these printouts at random time intervals: 
Updating sample is detected ... <23984>
Updating sample is detected ... < False >
Updating sample is detected ... <-15568>

Low level Tango device polling anomaly ?

**Comment by HilbertCorsair** [comment] 2024-10-11 16:42
It turns out that changing the polling from "events" to "300" in the xml configuration file fixes the problem.

**Closed as completed** 2024-10-11 16:43 UTC

**Comment by HilbertCorsair** [comment] 2024-10-11 16:44
Strange Tango polling bug for devices that are configured with polling = "events"

**Comment by marcus-oscarsson** [comment] 2024-10-14 08:24
Hm, do you think you can paste your configuration file working and not working ?

**Comment by HilbertCorsair** [comment] 2024-10-15 08:56
Shure, here is the initial configuration file for the PX1Cryotong HO (inherits from Cats90) which is our sample changer. 
https://github.com/HilbertCorsair/mxcubeweb_SOLEIL_PX1/blob/11cb4ae15a551208472987e40ad4cbec9cabde82/test/HardwareObjectsMockup.xml/cryotong.xml#L1

Two lines were deleted and the the polling for _chnSampleIsDetected was changed to "100" 
```
<object class = "PX1Cryotong">

  <username>CryoTong</username>
  <tangoname>i10-c-cx1/ex/catscryotong</tangoname>    
  <cats>i10-c-cx1/ex/cats</cats>
  <object role = "environment" hwrid = "/environment"></object>
  <useUpdateTimer>False</useUpdateTimer>
  <cm>CATS</cm>
  <nb_of_lids>1</nb_of_lids>
  <no_of_baskets>3</no_of_baskets>
  <samples_per_basket>16</samples_per_basket>

  <!-- <object role="environment" href="/environment" />  -->
 
  <!-- beware some channels are connected to PyCats server, not to cryotong server -->
  <command type="tango" tangoname="i10-c-cx1/ex/cats" name="_cmdScanSample">barcode</command>

  <!-- MAINTENANCE COMMANDS -->

  <command type="tango" name="_cmdReset">ResetError</command>
  <command type="tango" name="_cmdClearMemory">ClearMemory</command>
  <command type="tango" name="_cmdAckSampleMemory">AckIncoherentGonioSampleState</command>

  <command type="tango" name="_cmdOpenLid">OpenLid</command>
  <command type="tango" name="_cmdCloseLid">CloseLid</command>

  <command type="tango" name="_cmdOpenLid1">OpenLid</command>
  <command type="tango" name="_cmdCloseLid1">CloseLid</command>

  <command type="tango" name="_cmdHomeOpen">HomeOpen</command>

  <command type="tango" name="_cmdLoad">Mount</command>
  <command type="tango" name="_cmdUnload">UnMount</command>
  <command type="tango" name="_cmdChainedLoad">Exchange</command>

  <command type="tango" name="_cmdPowerOn">PowerOn</command>
  <command type="tango" name="_cmdPowerOff">PowerOff</command>


  <!-- channel type="tango" name="_chnToolOpen" polling="1000">toolOpen</channeli -->  <!-- Use for r/w command -->

  <channel type="tango" name="_chnSoftAuth" polling="events">beamlineMvtAuthorized</channel>
  <channel type="tango" name="_chnHomeOpened" polling="events">homeOpened</channel>
  <channel type="tango" name="_chnSafeNeeded" polling="events">safeNeeded</channel>
  <channel type="tango" name="_chnDryAndSoakNeeded" polling="events">dryAndSoakNeeded</channel>
  <channel type="tango" name="_chnIncoherentGonioSampleState" polling="events">incoherentGonioSampleState</channel>
  <channel type="tango" name="_chnCountDown" polling="events">countdown</channel>

  <channel type="tango" name="_chnPathRunning" polling="events">pathRunning</channel>

  <channel type="tango" name="_chnSampleIsDetected" polling="100">sampleIsDetected</channel>
  <channel type="tango" name="_chnCryoInserted" polling="events">cryoInserted</channel>

  <channel type="tango" polling="events" name="_chnBasket1State">puckIncassette1</channel>
  <channel type="tango" polling="events" name="_chnBasket2State">puckIncassette2</channel>
  <channel type="tango" polling="events" name="_chnBasket3State">puckIncassette3</channel>

  <channel type="tango" polling="1000" name="_chnLidLoadedSample">lidSampleOnDiff</channel>
  <channel type="tango" polling="1000" name="_chnNumLoadedSample">numSampleOnDiff</channel>


  <!-- CHANNELS FROM CATS --> 
  
  <channel type="tango" polling="events" tangoname="i10-c-cx1/ex/cats" name="_chnTotalLidState">di_AllLidsClosed</channel>
  <channel type="tango" polling="events" tangoname="i10-c-cx1/ex/cats" name="_chnSampleBarcode">Barcode</channel>
  <channel type="tango" polling="events" tangoname="i10-c-cx1/ex/cats" name="_chnPowered">Powered</channel>
  <channel type="tango" polling="events" tangoname="i10-c-cx1/ex/cats" name="_chnMessage">Message</channel>

</object>

```
These changes made sure that the configuration for _chnSampleIsDetected and _chnLid1State have polling in miliseconds instead of 'events'. The _chnLid1State was removed from the config file since it is already defined with polling in miliseconds in the Cats90 class. 
I also noticed that in the configuration file _chnSampleIsDetected was defined twice with polling 'events' in both cases so I removed one of the lines and changed the polling to 100 miliseconds in the remaining line configuring this channelObject. 
Flowing these changes both problems with the sampleIsDetected and Lid1State diapered and they no longer switch to numerical values.

**Comment by HilbertCorsair** [comment] 2024-10-15 09:04
You can notice that for _chnPowered the polling is still in events and this is still problematic but for now these changes ony deal with the _chnLid1State and _chnSampleIsDetected. From what I've noticed ChanelObject.connect_signal() has inconsistent behavior for all booleans. Tago version used could also be an issue. This could be a Tango bug that was patched in recent versions.
